name: CI/CD

on:
  push:
    branches:
      - main

  repository_dispatch:
    types: [stop_workflow]
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Information
        run: |
          echo "Workflow started"
          echo "Event type: $GITHUB_EVENT_NAME"
          echo "Event payload: $GITHUB_EVENT_PATH"

      - name: Checkout code
        uses: actions/checkout@v2
