name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    # You can specify the name of your self-hosted runner
    # runs-on: [self-hosted, my-custom-runner]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        npm install

    - name: Run Tests
      run: |
        npm test

    - name: Build
      run: |
        npm run build

    - name: Save Runner Logs
      run: |
        mkdir -p $RUNNER_WORKSPACE/_logs
        move C:\Users\NIHAR\OneDrive\Desktop\actions-runner\runner.log $RUNNER_WORKSPACE\_logs\runner.log
