name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    # You can specify the name of your self-hosted runner
    # runs-on: [self-hosted, my-custom-runner]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        npm install

    - name: Run Tests
      run: |
        npm test

    - name: Build
      run: |
        npm run build

    # Configure the runner to store logs locally
    - name: Configure runner logs
      run: |
        mkdir -p $RUNNER_WORKSPACE/_logs
        echo "::set-env name=ACTIONS_RUNNER_DEBUG_LOG_FILE::$RUNNER_WORKSPACE/_logs/runner.log"
